# Generated by Django 4.2 on 2023-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_sorting', '0002_wastecontainer_img_alter_waste_waste_name_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waste',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='wastecontainer',
            options={},
        ),
        migrations.RenameField(
            model_name='waste',
            old_name='type',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='waste',
            old_name='waste_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wastecontainer',
            old_name='cont_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='wastecontainer',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
