# Generated by Django 4.2 on 2023-04-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_sorting', '0004_rename_wastecontainer_container'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('type',)},
        ),
    ]
