# Generated by Django 4.2 on 2023-04-11 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import waste_sorting.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_sorting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecontainer',
            name='img',
            field=models.ImageField(default='bg.jpg', upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waste',
            name='waste_name',
            field=waste_sorting.models.NameField(max_length=150),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(max_length=10)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=140)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
