# Generated by Django 4.2 on 2023-04-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_sorting', '0003_alter_waste_options_alter_wastecontainer_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WasteContainer',
            new_name='Container',
        ),
    ]
