# Generated by Django 4.2 on 2023-04-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_sorting', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
