# Generated by Django 4.2 on 2023-04-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_sorting', '0009_remove_report_post_remove_report_reported_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
